export const GET_DATA = 'GET_DATA';
export const NEXT = 'NEXT';
export const BACK = 'BACK';
export const RESET_CURRENT_STEP_INDICATOR = 'RESET_CURRENT_STEP_INDICATOR';
export const SELECTED_CURRENT_ID_FOR_NEXT = 'SELECTED_CURRENT_ID_FOR_NEXT';
export const SELECTED_CURRENT_DESCRIPTION_FOR_NEXT =
  'SELECTED_CURRENT_DESCRIPTION_FOR_NEXT';
export const SELECTED_ID_FOR_SUBGENRES = 'SELECTED_ID_FOR_SUBGENRES';
export const SELECTED_ID_AFTER_SUB = 'SELECTED_ID_AFTER_SUB';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_STEP_MODE = 'CHANGE_STEP_MODE';
export const NEW_GENRE_FIELD = 'NEW_GENRE_FIELD';
export const NEW_GENRE_CHECKBOX = 'NEW_GENRE_CHECKBOX';
export const UPDATE_FIELD_INFORMATION = 'UPDATE_FIELD_INFORMATION';
export const RESET_FIELD_INFORMATION = 'RESET_FIELD_INFORMATION';
